// Единый перечень кодов ошибок API (раздел 7 ТЗ).
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNSUPPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
  ANALYSIS_IN_PROGRESS = 'ANALYSIS_IN_PROGRESS',
  ANALYSIS_FAILED = 'ANALYSIS_FAILED',
  NLP_SERVICE_UNAVAILABLE = 'NLP_SERVICE_UNAVAILABLE',
  RATE_LIMITED = 'RATE_LIMITED',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
